# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c1d31b88697afd8aba9f384911871fe8"
name = "best-selling-products"
handle = "best-selling-products-5"
application_url = "https://criteria-fever-dramatically-included.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://criteria-fever-dramatically-included.trycloudflare.com/auth/callback",
  "https://criteria-fever-dramatically-included.trycloudflare.com/auth/shopify/callback",
  "https://criteria-fever-dramatically-included.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
